export const LANGUAGES = {
  ENGLISH: 'english',
  URDU: 'urdu'
};

export const LANGUAGE_NAMES = {
  [LANGUAGES.ENGLISH]: 'English',
  [LANGUAGES.URDU]: 'اردو'
};



export const AGRICULTURE_CATEGORIES = {
  CROP_DISEASE: 'crop_disease',
  PEST_MANAGEMENT: 'pest_management',
  SOIL_HEALTH: 'soil_health',
  IRRIGATION: 'irrigation',
  FERTILIZER: 'fertilizer',
  GENERAL: 'general'
};

export const SAMPLE_QUESTIONS = {
  [LANGUAGES.ENGLISH]: [
    "How to treat rust fungus in wheat?",
    "Best fertilizer for rice crops?",
    "How to prevent cotton leaf curl virus?",
    "Water requirements for sugarcane?",
    "Organic pest control methods?"
  ],
  [LANGUAGES.URDU]: [
    "گندم میں زنگ کے پھپھوندی کا علاج کیسے کریں؟",
    "چاول کی فصل کے لیے بہترین کھاد کون سی ہے؟",
    "کپاس کی پتی کَرل وائرس سے کیسے بچائیں؟",
    "گنے کے لیے پانی کی کتنی ضرورت ہے؟",
    "نامیاتی کیڑے مارنے کے طریقے کون سے ہیں؟"
  ]
};


export const UI_TEXT = {
  [LANGUAGES.ENGLISH]: {
    // App
    appName: 'AgriGPT-PK',
    tagline: 'AI Agricultural Assistant for Pakistani Farmers',
    welcome: 'Welcome to AgriGPT-PK',
    description: 'Get instant agricultural advice for your crops through AI-powered analysis of text, images, and voice notes.',
    
    // Navigation
    home: 'Home',
    chat: 'Chat',
    upload: 'Upload',
    history: 'History',
    about: 'About',
    
    // Features
    textChat: 'Text Chat',
    imageAnalysis: 'Image Analysis',
    voiceNotes: 'Voice Notes',
    askQuestion: 'Ask your agricultural question...',
    uploadImage: 'Upload Crop Image',
    recordVoice: 'Record Voice Note',
    getAdvice: 'Get Advice',
    send: 'Send',
    processing: 'Processing...',
    
    // Results
    agriculturalAdvice: 'Agricultural Advice',
    analysisResults: 'Analysis Results',
    detectedIssues: 'Detected Issues',
    recommendations: 'Recommendations',
    
    // Actions
    startChat: 'Start Chat',
    browseFiles: 'Browse Files',
    dragDrop: 'Drag & drop files here',
    or: 'or',
    
    // Messages
    noMessages: 'No messages yet. Start a conversation!',
    typeMessage: 'Type your message...',
    uploading: 'Uploading...',
    analyzing: 'Analyzing...',
    
    // Errors
    error: 'Error',
    tryAgain: 'Try Again',
    fileTooLarge: 'File too large. Maximum size is 10MB.',
    invalidFileType: 'Invalid file type.',
    networkError: 'Network error. Please check your connection.',
    
    // About
    aboutTitle: 'About AgriGPT-PK',
    aboutDescription: 'AgriGPT-PK is an AI-powered agricultural assistant designed specifically for Pakistani farmers. Our mission is to make agricultural expertise accessible to every farmer through modern technology.',
    features: 'Features',
    howItWorks: 'How It Works',
    contact: 'Contact',
    
    // History
    recentQueries: 'Recent Queries',
    noHistory: 'No query history yet.',
    clearHistory: 'Clear History',
    
    // Additional translations
    clear: 'Clear',
    clearChat: 'Clear Chat',
    you: 'You',
    agriGPT: 'AgriGPT',
    copy: 'Copy',
    copied: 'Copied',
    copyToClipboard: 'Copy to Clipboard',
    aiTyping: 'AI is typing...',
    startConversation: 'Start a conversation to get agricultural advice',
    aiPoweredAssistant: 'AI-Powered Assistant',
    sampleQuestion1: 'How to treat rust fungus in wheat?',
    sampleQuestion2: 'Best fertilizer for rice crops?',
    sampleQuestion3: 'How to prevent cotton leaf curl virus?',
    sampleQuestion4: 'Water requirements for sugarcane?',
    sampleQuestion5: 'Organic pest control methods?',
    quickQuestions: 'Quick Questions',
    image: 'Image',
    voiceMessage: 'Voice Message',
    supportedFormats: 'Supported formats',
    maxSize: 'Max size',
    navigation: 'Navigation',
    allRightsReserved: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    aboutDescription: 'AgriGPT-PK is an AI-powered agricultural assistant designed specifically for Pakistani farmers.',
    textChatDescription: 'Get instant answers to your agricultural questions through text chat',
    imageAnalysisDescription: 'Upload crop images for AI-powered disease detection and analysis',
    voiceNotesDescription: 'Record voice notes and get instant agricultural advice',
    farmersHelped: 'Farmers Helped',
    queriesAnswered: 'Queries Answered',
    accuracyRate: 'Accuracy Rate',
    supportAvailable: 'Support Available',
    featuresDescription: 'Discover powerful features designed for Pakistani farmers',
    sampleQuestions: 'Sample Questions',
    sampleQuestionsDescription: 'Try asking these common agricultural questions',
    readyToStart: 'Ready to Start?',
    ctaDescription: 'Join thousands of farmers getting instant agricultural advice',
    startChatNow: 'Start Chat Now',
    learnMore: 'Learn More',
    agriculturalChat: 'Agricultural Chat',
    chatDescription: 'Get instant answers to your agricultural questions',
    tips: 'Tips',
    tipBeSpecific: 'Be specific in your questions',
    tipUploadImages: 'Upload images for better analysis',
    tipUseVoice: 'Use voice notes for convenience',
    tipCheckHistory: 'Check history for past queries',
    statistics: 'Statistics',
    queriesToday: 'Queries Today',
    queriesThisWeek: 'Queries This Week',
    chatHistory: 'Chat History',
    savedResponses: 'Saved Responses',
    noHistoryYet: 'No history yet',
    historyDescription: 'Your chat history will appear here',
    noSavedResponses: 'No saved responses',
    savedDescription: 'Save important responses for later reference',
    uploadAnalysis: 'Upload & Analysis',
    uploadDescription: 'Upload images or voice notes for AI analysis',
    transcription: 'Transcription',
    symptoms: 'Symptoms',
    severity: 'Severity',
    confidenceScore: 'Confidence Score',
    noResultsYet: 'No results yet',
    uploadToSeeResults: 'Upload a file to see analysis results',
    analysisInProgress: 'Analysis in progress, please wait...',
    aboutAgriGPT: 'About AgriGPT-PK',
    ourMission: 'Our Mission',
    missionDescription: 'To empower Pakistani farmers with AI-powered agricultural expertise',
    keyFeatures: 'Key Features',
    featuresOverview: 'Discover what makes AgriGPT-PK special',
    aiPowered: 'AI Powered',
    bilingual: 'Bilingual',
    instantResults: 'Instant Results',
    howItWorksDescription: 'Simple steps to get agricultural advice',
    step1Title: 'Ask Your Question',
    step1Description: 'Type your agricultural question or upload an image',
    step2Title: 'AI Analysis',
    step2Description: 'Our AI analyzes your query and provides insights',
    step3Title: 'Get Recommendations',
    step3Description: 'Receive detailed recommendations and solutions',
    step4Title: 'Take Action',
    step4Description: 'Apply the advice to improve your crops',
    ourTeam: 'Our Team',
    teamDescription: 'Meet the team behind AgriGPT-PK',
    teamLead: 'Team Lead',
    backendEngineer: 'Backend Engineer',
    mlEngineer: 'ML Engineer',
    frontendDeveloper: 'Frontend Developer',
    whatsappSpecialist: 'WhatsApp Specialist',
    documentationSpecialist: 'Documentation Specialist',
    ahsanDescription: 'Leading the AgriGPT-PK project',
    backendEngineerDescription: 'Building robust backend systems',
    mlEngineerDescription: 'Developing AI models for agriculture',
    frontendDeveloperDescription: 'Creating beautiful user interfaces',
    whatsappSpecialistDescription: 'Integrating WhatsApp functionality',
    documentationSpecialistDescription: 'Writing comprehensive documentation',
    getInTouch: 'Get In Touch',
    contactDescription: 'Have questions? We\'d love to hear from you',
    email: 'Email',
    phone: 'Phone',
    downloadApp: 'Download App',
    aiPoweredDescription: 'Powered by advanced AI technology',
    bilingualSupport: 'Bilingual Support',
    bilingualSupportDescription: 'Available in Urdu and English',
    imageAnalysisDescription: 'Upload images for disease detection',
    voiceProcessing: 'Voice Processing',
    voiceProcessingDescription: 'Record and transcribe voice notes',
    whatsappIntegration: 'WhatsApp Integration',
    whatsappIntegrationDescription: 'Get advice via WhatsApp',
    mobileFriendly: 'Mobile Friendly',
    mobileFriendlyDescription: 'Works perfectly on all devices',
    microphoneAccessDenied: 'Microphone access denied',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    uploadAudio: 'Upload Audio',
    audioPreview: 'Audio Preview',
    playing: 'Playing',
    readyToPlay: 'Ready to Play',
    processingAudio: 'Processing Audio...',
    imagePreview: 'Image Preview',
    fileName: 'File Name',
    fileSize: 'File Size',
    dimensions: 'Dimensions',
    uploading: 'Uploading...',
    complete: 'Complete',
    analyzingImage: 'Analyzing Image...',
    queryHistory: 'Query History',
    allQueries: 'All Queries',
    textQueries: 'Text Queries',
    imageQueries: 'Image Queries',
    voiceQueries: 'Voice Queries',
    totalQueries: 'Total Queries',
    yourQueries: 'Your Queries',
    aiResponses: 'AI Responses',
    successRate: 'Success Rate',
    filters: 'Filters',
    searchHistory: 'Search History',
    showing: 'Showing',
    of: 'of',
    queries: 'queries',
    noResultsFound: 'No results found',
    tryDifferentSearch: 'Try a different search',
    startChattingToSeeHistory: 'Start chatting to see history',
    queryDetails: 'Query Details',
    query: 'Query',
    response: 'Response',
    metadata: 'Metadata',
    type: 'Type',
    timestamp: 'Timestamp',
    status: 'Status',
    analysis: 'Analysis',
    imageAnalysisPerformed: 'Image analysis performed',
    voiceMessageProcessed: 'Voice message processed',
    textQuery: 'Text Query',
    imageQuery: 'Image Query',
    voiceQuery: 'Voice Query',
    confirmClearHistory: 'Are you sure you want to clear all history?',
    sent: 'Sent',
    delivered: 'Delivered',
    failed: 'Failed',
    
    // Auth
    login: 'Login',
    signUp: 'Sign Up',
    logout: 'Logout',
    loginDescription: 'Sign in to your account to continue',
    signupDescription: 'Create a new account to get started',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterFullName: 'Enter your full name',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    loggingIn: 'Logging in...',
    creatingAccount: 'Creating account...',
    allFieldsRequired: 'All fields are required',
    invalidCredentials: 'Invalid email or password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    signupFailed: 'Failed to create account. Please try again.',
    passwordRequirements: 'Password must be at least 6 characters',
    iAgreeTo: 'I agree to the',
    and: 'and',
    demoMode: 'Demo Mode',
    useAnyCredentials: 'Use any email and password to login',
    
    // OTP
    sendOTP: 'Send OTP',
    verifyOTP: 'Verify OTP',
    enterOTP: 'Enter OTP',
    otpSentTo: 'OTP sent to',
    otpExpiresIn: 'OTP expires in',
    otpValidFor2Minutes: 'OTP is valid for 2 minutes',
    resendOTP: 'Resend OTP',
    sendingOTP: 'Sending OTP...',
    verifying: 'Verifying...',
    enterValidOTP: 'Please enter a valid 6-digit OTP',
    back: 'Back',
    loginSuccessful: 'Login successful!',
    otpSentSuccessfully: 'OTP sent to your email successfully',
    otpVerifiedSuccessfully: 'OTP verified successfully!',
    accountCreatedSuccessfully: 'Account created successfully!'
  },
  [LANGUAGES.URDU]: {
    // App
    appName: 'ایگری جی پی ٹی-پاکستان',
    tagline: 'پاکستانی کسانوں کے لیے AI زرعی معاون',
    welcome: 'ایگری جی پی ٹی-پاکستان میں خوش آمدید',
    description: 'ٹیکسٹ، تصاویر اور وائس نوٹس کے AI پر مبنی تجزیے کے ذریعے اپنی فصلوں کے لیے فوری زرعی مشورہ حاصل کریں۔',
    
    // Navigation
    home: 'ہوم',
    chat: 'چیٹ',
    upload: 'اپ لوڈ',
    history: 'تاریخ',
    about: 'ہمارے بارے میں',
    
    // Features
    textChat: 'ٹیکسٹ چیٹ',
    imageAnalysis: 'تصویر کا تجزیہ',
    voiceNotes: 'وائس نوٹس',
    askQuestion: 'اپنا زرعی سوال پوچھیں...',
    uploadImage: 'فصل کی تصویر اپ لوڈ کریں',
    recordVoice: 'وائس نوٹ ریکارڈ کریں',
    getAdvice: 'مشورہ حاصل کریں',
    send: 'بھیجیں',
    processing: 'پروسس ہو رہا ہے...',
    
    // Results
    agriculturalAdvice: 'زرعی مشورہ',
    analysisResults: 'تجزیے کے نتائج',
    detectedIssues: 'پائے گئے مسائل',
    recommendations: 'تجاویز',
    
    // Actions
    startChat: 'چیٹ شروع کریں',
    browseFiles: 'فائلیں براؤز کریں',
    dragDrop: 'فائلیں یہاں ڈریگ اینڈ ڈراپ کریں',
    or: 'یا',
    
    // Messages
    noMessages: 'ابھی تک کوئی پیغامات نہیں۔ بات چیت شروع کریں!',
    typeMessage: 'اپنا پیغام ٹائپ کریں...',
    uploading: 'اپ لوڈ ہو رہا ہے...',
    analyzing: 'تجزیہ ہو رہا ہے...',
    
    // Errors
    error: 'خرابی',
    tryAgain: 'دوبارہ کوشش کریں',
    fileTooLarge: 'فائل بہت بڑی ہے۔ زیادہ سے زیادہ سائز 10MB ہے۔',
    invalidFileType: 'غلط فائل کی قسم۔',
    networkError: 'نیٹ ورک خرابی۔ براہ کرم اپنا کنکشن چیک کریں۔',
    
    // About
    aboutTitle: 'ایگری جی پی ٹی-پاکستان کے بارے میں',
    aboutDescription: 'ایگری جی پی ٹی-پاکستان ایک AI پر مبنی زرعی معاون ہے جو خاص طور پر پاکستانی کسانوں کے لیے ڈیزائن کیا گیا ہے۔ ہمارا مشن جدید ٹیکنالوجی کے ذریعے ہر کسان کو زرعی مہارت تک رسائی فراہم کرنا ہے۔',
    features: 'خصوصیات',
    howItWorks: 'یہ کیسے کام کرتا ہے',
    contact: 'رابطہ',
    
    // History
    recentQueries: 'حالیہ سوالات',
    noHistory: 'ابھی تک کوئی سوالات کی تاریخ نہیں۔',
    clearHistory: 'تاریخ صاف کریں',
    
    // Additional translations
    clear: 'صاف کریں',
    clearChat: 'چیٹ صاف کریں',
    you: 'آپ',
    agriGPT: 'ایگری جی پی ٹی',
    copy: 'کاپی',
    copied: 'کاپی ہو گیا',
    copyToClipboard: 'کلپ بورڈ پر کاپی کریں',
    aiTyping: 'AI ٹائپ کر رہا ہے...',
    startConversation: 'زرعی مشورہ حاصل کرنے کے لیے بات چیت شروع کریں',
    aiPoweredAssistant: 'AI پر مبنی معاون',
    sampleQuestion1: 'گندم میں زنگ کے پھپھوندی کا علاج کیسے کریں؟',
    sampleQuestion2: 'چاول کی فصل کے لیے بہترین کھاد کون سی ہے؟',
    sampleQuestion3: 'کپاس کی پتی کَرل وائرس سے کیسے بچائیں؟',
    sampleQuestion4: 'گنے کے لیے پانی کی کتنی ضرورت ہے؟',
    sampleQuestion5: 'نامیاتی کیڑے مارنے کے طریقے کون سے ہیں؟',
    quickQuestions: 'فوری سوالات',
    image: 'تصویر',
    voiceMessage: 'وائس پیغام',
    supportedFormats: 'معاون فارمیٹس',
    maxSize: 'زیادہ سے زیادہ سائز',
    navigation: 'نیویگیشن',
    allRightsReserved: 'تمام حقوق محفوظ ہیں',
    privacyPolicy: 'پرائیویسی پالیسی',
    termsOfService: 'سروس کی شرائط',
    aboutDescription: 'ایگری جی پی ٹی-پاکستان ایک AI پر مبنی زرعی معاون ہے جو خاص طور پر پاکستانی کسانوں کے لیے ڈیزائن کیا گیا ہے۔',
    textChatDescription: 'ٹیکسٹ چیٹ کے ذریعے اپنے زرعی سوالات کے فوری جوابات حاصل کریں',
    imageAnalysisDescription: 'AI پر مبنی بیماری کی تشخیص اور تجزیے کے لیے فصل کی تصاویر اپ لوڈ کریں',
    voiceNotesDescription: 'وائس نوٹس ریکارڈ کریں اور فوری زرعی مشورہ حاصل کریں',
    farmersHelped: 'کسانوں کی مدد',
    queriesAnswered: 'سوالات کے جوابات',
    accuracyRate: 'درستگی کی شرح',
    supportAvailable: 'سپورٹ دستیاب',
    featuresDescription: 'پاکستانی کسانوں کے لیے ڈیزائن کردہ طاقتور خصوصیات دریافت کریں',
    sampleQuestions: 'نمونہ سوالات',
    sampleQuestionsDescription: 'یہ عام زرعی سوالات پوچھ کر دیکھیں',
    readyToStart: 'شروع کرنے کے لیے تیار؟',
    ctaDescription: 'ہزاروں کسانوں میں شامل ہوں جو فوری زرعی مشورہ حاصل کر رہے ہیں',
    startChatNow: 'ابھی چیٹ شروع کریں',
    learnMore: 'مزید جانیں',
    agriculturalChat: 'زرعی چیٹ',
    chatDescription: 'اپنے زرعی سوالات کے فوری جوابات حاصل کریں',
    tips: 'نکات',
    tipBeSpecific: 'اپنے سوالات میں مخصوص رہیں',
    tipUploadImages: 'بہتر تجزیے کے لیے تصاویر اپ لوڈ کریں',
    tipUseVoice: 'سہولت کے لیے وائس نوٹس استعمال کریں',
    tipCheckHistory: 'گذشتہ سوالات کے لیے تاریخ چیک کریں',
    statistics: 'اعداد و شمار',
    queriesToday: 'آج کے سوالات',
    queriesThisWeek: 'اس ہفتے کے سوالات',
    chatHistory: 'چیٹ کی تاریخ',
    savedResponses: 'محفوظ شدہ جوابات',
    noHistoryYet: 'ابھی تک کوئی تاریخ نہیں',
    historyDescription: 'آپ کی چیٹ کی تاریخ یہاں ظاہر ہوگی',
    noSavedResponses: 'کوئی محفوظ شدہ جوابات نہیں',
    savedDescription: 'بعد میں حوالہ کے لیے اہم جوابات محفوظ کریں',
    uploadAnalysis: 'اپ لوڈ اور تجزیہ',
    uploadDescription: 'AI تجزیے کے لیے تصاویر یا وائس نوٹس اپ لوڈ کریں',
    transcription: 'ٹرانسکرپشن',
    symptoms: 'علامات',
    severity: 'شدت',
    confidenceScore: 'اعتماد کا اسکور',
    noResultsYet: 'ابھی تک کوئی نتائج نہیں',
    uploadToSeeResults: 'تجزیے کے نتائج دیکھنے کے لیے فائل اپ لوڈ کریں',
    analysisInProgress: 'تجزیہ جاری ہے، براہ کرم انتظار کریں...',
    aboutAgriGPT: 'ایگری جی پی ٹی-پاکستان کے بارے میں',
    ourMission: 'ہمارا مشن',
    missionDescription: 'پاکستانی کسانوں کو AI پر مبنی زرعی مہارت سے بااختیار بنانا',
    keyFeatures: 'اہم خصوصیات',
    featuresOverview: 'دریافت کریں کہ ایگری جی پی ٹی-پاکستان کو کیا خاص بناتا ہے',
    aiPowered: 'AI پر مبنی',
    bilingual: 'دو لسانی',
    instantResults: 'فوری نتائج',
    howItWorksDescription: 'زرعی مشورہ حاصل کرنے کے آسان مراحل',
    step1Title: 'اپنا سوال پوچھیں',
    step1Description: 'اپنا زرعی سوال ٹائپ کریں یا تصویر اپ لوڈ کریں',
    step2Title: 'AI تجزیہ',
    step2Description: 'ہمارا AI آپ کے سوال کا تجزیہ کرتا ہے اور بصیرت فراہم کرتا ہے',
    step3Title: 'تجاویز حاصل کریں',
    step3Description: 'تفصیلی تجاویز اور حل حاصل کریں',
    step4Title: 'عمل کریں',
    step4Description: 'اپنی فصلوں کو بہتر بنانے کے لیے مشورہ لاگو کریں',
    ourTeam: 'ہماری ٹیم',
    teamDescription: 'ایگری جی پی ٹی-پاکستان کے پیچھے ٹیم سے ملیں',
    teamLead: 'ٹیم لیڈ',
    backendEngineer: 'بیک اینڈ انجینئر',
    mlEngineer: 'ML انجینئر',
    frontendDeveloper: 'فرنٹ اینڈ ڈویلپر',
    whatsappSpecialist: 'واٹس ایپ اسپیشلسٹ',
    documentationSpecialist: 'دستاویزات اسپیشلسٹ',
    ahsanDescription: 'ایگری جی پی ٹی-پاکستان پروجیکٹ کی قیادت',
    backendEngineerDescription: 'مضبوط بیک اینڈ سسٹم بنانا',
    mlEngineerDescription: 'زراعت کے لیے AI ماڈل تیار کرنا',
    frontendDeveloperDescription: 'خوبصورت یوزر انٹرفیس بنانا',
    whatsappSpecialistDescription: 'واٹس ایپ کی فعالیت کو مربوط کرنا',
    documentationSpecialistDescription: 'جامع دستاویزات لکھنا',
    getInTouch: 'رابطہ کریں',
    contactDescription: 'سوالات ہیں؟ ہم آپ سے سننا پسند کریں گے',
    email: 'ای میل',
    phone: 'فون',
    downloadApp: 'ایپ ڈاؤن لوڈ کریں',
    aiPoweredDescription: 'جدید AI ٹیکنالوجی سے چلایا گیا',
    bilingualSupport: 'دو لسانی سپورٹ',
    bilingualSupportDescription: 'اردو اور انگریزی میں دستیاب',
    imageAnalysisDescription: 'بیماری کی تشخیص کے لیے تصاویر اپ لوڈ کریں',
    voiceProcessing: 'وائس پروسیسنگ',
    voiceProcessingDescription: 'وائس نوٹس ریکارڈ اور ٹرانسکرائب کریں',
    whatsappIntegration: 'واٹس ایپ انضمام',
    whatsappIntegrationDescription: 'واٹس ایپ کے ذریعے مشورہ حاصل کریں',
    mobileFriendly: 'موبائل دوستانہ',
    mobileFriendlyDescription: 'تمام آلات پر بہترین کام کرتا ہے',
    microphoneAccessDenied: 'مائیکروفون تک رسائی مسترد',
    startRecording: 'ریکارڈنگ شروع کریں',
    stopRecording: 'ریکارڈنگ بند کریں',
    uploadAudio: 'آڈیو اپ لوڈ کریں',
    audioPreview: 'آڈیو پیش منظر',
    playing: 'چل رہا ہے',
    readyToPlay: 'چلانے کے لیے تیار',
    processingAudio: 'آڈیو پروسیس ہو رہا ہے...',
    imagePreview: 'تصویر کا پیش منظر',
    fileName: 'فائل کا نام',
    fileSize: 'فائل کا سائز',
    dimensions: 'جہتیں',
    uploading: 'اپ لوڈ ہو رہا ہے...',
    complete: 'مکمل',
    analyzingImage: 'تصویر کا تجزیہ ہو رہا ہے...',
    queryHistory: 'سوالات کی تاریخ',
    allQueries: 'تمام سوالات',
    textQueries: 'ٹیکسٹ سوالات',
    imageQueries: 'تصویری سوالات',
    voiceQueries: 'وائس سوالات',
    totalQueries: 'کل سوالات',
    yourQueries: 'آپ کے سوالات',
    aiResponses: 'AI جوابات',
    successRate: 'کامیابی کی شرح',
    filters: 'فلٹرز',
    searchHistory: 'تاریخ تلاش کریں',
    showing: 'دکھا رہا ہے',
    of: 'کا',
    queries: 'سوالات',
    noResultsFound: 'کوئی نتائج نہیں ملے',
    tryDifferentSearch: 'مختلف تلاش کریں',
    startChattingToSeeHistory: 'تاریخ دیکھنے کے لیے چیٹ شروع کریں',
    queryDetails: 'سوال کی تفصیلات',
    query: 'سوال',
    response: 'جواب',
    metadata: 'میٹا ڈیٹا',
    type: 'قسم',
    timestamp: 'وقت',
    status: 'حالت',
    analysis: 'تجزیہ',
    imageAnalysisPerformed: 'تصویر کا تجزیہ کیا گیا',
    voiceMessageProcessed: 'وائس پیغام پروسیس کیا گیا',
    textQuery: 'ٹیکسٹ سوال',
    imageQuery: 'تصویری سوال',
    voiceQuery: 'وائس سوال',
    confirmClearHistory: 'کیا آپ واقعی تمام تاریخ صاف کرنا چاہتے ہیں؟',
    sent: 'بھیجا گیا',
    delivered: 'پہنچایا گیا',
    failed: 'ناکام',
    
    // Auth
    login: 'لاگ ان',
    signUp: 'سائن اپ',
    logout: 'لاگ آؤٹ',
    loginDescription: 'جاری رکھنے کے لیے اپنے اکاؤنٹ میں سائن ان کریں',
    signupDescription: 'شروع کرنے کے لیے نیا اکاؤنٹ بنائیں',
    email: 'ای میل',
    password: 'پاس ورڈ',
    fullName: 'پورا نام',
    confirmPassword: 'پاس ورڈ کی تصدیق کریں',
    enterEmail: 'اپنا ای میل درج کریں',
    enterPassword: 'اپنا پاس ورڈ درج کریں',
    enterFullName: 'اپنا پورا نام درج کریں',
    rememberMe: 'مجھے یاد رکھیں',
    forgotPassword: 'پاس ورڈ بھول گئے؟',
    dontHaveAccount: 'اکاؤنٹ نہیں ہے؟',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟',
    loggingIn: 'لاگ ان ہو رہا ہے...',
    creatingAccount: 'اکاؤنٹ بنایا جا رہا ہے...',
    allFieldsRequired: 'تمام فیلڈز درکار ہیں',
    invalidCredentials: 'غلط ای میل یا پاس ورڈ',
    passwordsDoNotMatch: 'پاس ورڈز میل نہیں کھاتے',
    passwordTooShort: 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
    signupFailed: 'اکاؤنٹ بنانے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    passwordRequirements: 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
    iAgreeTo: 'میں اس سے متفق ہوں',
    and: 'اور',
    demoMode: 'ڈیمو موڈ',
    useAnyCredentials: 'لاگ ان کرنے کے لیے کوئی بھی ای میل اور پاس ورڈ استعمال کریں',
    
    // OTP
    sendOTP: 'OTP بھیجیں',
    verifyOTP: 'OTP کی تصدیق کریں',
    enterOTP: 'OTP درج کریں',
    otpSentTo: 'OTP بھیجا گیا',
    otpExpiresIn: 'OTP ختم ہوگا',
    otpValidFor2Minutes: 'OTP 2 منٹ کے لیے درست ہے',
    resendOTP: 'OTP دوبارہ بھیجیں',
    sendingOTP: 'OTP بھیجا جا رہا ہے...',
    verifying: 'تصدیق ہو رہی ہے...',
    enterValidOTP: 'براہ کرم 6 ہندسوں کا درست OTP درج کریں',
    back: 'واپس',
    loginSuccessful: 'لاگ ان کامیاب!',
    otpSentSuccessfully: 'OTP آپ کے ای میل پر بھیج دیا گیا',
    otpVerifiedSuccessfully: 'OTP کی تصدیق کامیاب!',
    accountCreatedSuccessfully: 'اکاؤنٹ کامیابی سے بنایا گیا!'
  }
};